// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTS.Host.Persistence;

#nullable disable

namespace PTS.Host.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826121826_WorkspaceResourceAuthorization")]
    partial class WorkspaceResourceAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTS.Host.Persistence.Testing.TenantIsolationTestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tenant_isolation_test_records");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_isolation_test_records_tenant_id");

                    b.ToTable("tenant_isolation_test_records", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Identity.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_credentials_email");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.PlatformAdministration.PlatformAdministrator", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.HasKey("UserId")
                        .HasName("pk_platform_administrators");

                    b.ToTable("platform_administrators", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_memberships_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_memberships_tenant_id");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_user_id_tenant_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_projects_tenant_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_projects_workspace_id");

                    b.HasIndex("TenantId", "WorkspaceId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_workspaces_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspaces_tenant_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkspaceAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_level");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_access");

                    b.HasIndex("TenantId", "WorkspaceId")
                        .HasDatabaseName("ix_workspace_access_tenant_workspace");

                    b.HasIndex("TenantId", "MembershipId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_access_tenant_membership_workspace");

                    b.ToTable("workspace_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_access_access_level", "access_level IN ('View', 'Edit')");
                        });
                });

            modelBuilder.Entity("PTS.Host.Persistence.Testing.TenantIsolationTestRecord", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_isolation_test_records_tenants_tenant_id");
                });

            modelBuilder.Entity("PTS.Modules.Identity.UserCredential", b =>
                {
                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PTS.Modules.Identity.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.PlatformAdministration.PlatformAdministrator", b =>
                {
                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platform_administrators_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Membership", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Project", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_tenants_tenant_id");

                    b.HasOne("PTS.Modules.WorkManagement.Workspace", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkspaceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_workspaces_tenant_id_workspace_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Workspace", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_tenants_tenant_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkspaceAccess", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_memberships_tenant_id_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.Workspace", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkspaceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_workspaces_tenant_id_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
