// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTS.Host.Persistence;

#nullable disable

namespace PTS.Host.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829083242_TaskTicketCollaboration")]
    partial class TaskTicketCollaboration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTS.Host.Persistence.Testing.TenantIsolationTestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tenant_isolation_test_records");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_isolation_test_records_tenant_id");

                    b.ToTable("tenant_isolation_test_records", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Identity.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_credentials_email");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.PlatformAdministration.PlatformAdministrator", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.HasKey("UserId")
                        .HasName("pk_platform_administrators");

                    b.ToTable("platform_administrators", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_memberships_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_memberships_tenant_id");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_user_id_tenant_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasAlternateKey("TenantId", "WorkspaceId", "Id")
                        .HasName("ak_projects_tenant_id_workspace_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_projects_tenant_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_projects_workspace_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RecipientMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_membership_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TenantId", "TaskId");

                    b.HasIndex("TenantId", "RecipientMembershipId", "IsRead")
                        .HasDatabaseName("ix_notifications_tenant_recipient_unread");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_type", "type IN ('TaskAssigned','TaskReassigned','TaskCommentAdded','TaskPriorityChanged','TaskDeadlineChanged','TaskStatusChanged','TaskTagChanged','TaskUpdated','TaskClosed','TaskReopened')");
                        });
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_tags_tenant_id_id");

                    b.HasIndex("TenantId", "CreatedByMembershipId");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_tenant_normalized_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_membership_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_tasks_tenant_id_id");

                    b.HasIndex("TenantId", "AssignedMembershipId")
                        .HasDatabaseName("ix_tasks_tenant_assignee");

                    b.HasIndex("TenantId", "CreatedByMembershipId");

                    b.HasIndex("TenantId", "ProjectId")
                        .HasDatabaseName("ix_tasks_tenant_project");

                    b.HasIndex("TenantId", "WorkspaceId")
                        .HasDatabaseName("ix_tasks_tenant_workspace");

                    b.HasIndex("TenantId", "WorkspaceId", "ProjectId");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('Low', 'Normal', 'High', 'Urgent')");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('Open', 'InProgress', 'Waiting', 'Resolved', 'Closed')");
                        });
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_task_activities");

                    b.HasIndex("TenantId", "ActorMembershipId");

                    b.HasIndex("TenantId", "TaskId", "CreatedAtUtc")
                        .HasDatabaseName("ix_task_activities_tenant_task_created");

                    b.ToTable("task_activities", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_activities_event_type", "event_type IN ('TaskCreated','TitleChanged','DescriptionChanged','PriorityChanged','DeadlineChanged','StatusChanged','AssigneeChanged','TagAdded','TagRemoved','CommentAdded','CommentEdited','CommentDeleted','TaskReopened')");
                        });
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_membership_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("TenantId", "AuthorMembershipId");

                    b.HasIndex("TenantId", "TaskId", "CreatedAtUtc")
                        .HasDatabaseName("ix_task_comments_tenant_task_created");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskReadState", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("LastViewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at_utc");

                    b.HasKey("TenantId", "TaskId", "MembershipId")
                        .HasName("pk_task_read_states");

                    b.HasIndex("TenantId", "MembershipId");

                    b.ToTable("task_read_states", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskTag", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TenantId", "TaskId", "TagId")
                        .HasName("pk_task_tags");

                    b.HasIndex("TenantId", "TagId");

                    b.ToTable("task_tags", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_workspaces_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspaces_tenant_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkspaceAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_level");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_access");

                    b.HasIndex("TenantId", "WorkspaceId")
                        .HasDatabaseName("ix_workspace_access_tenant_workspace");

                    b.HasIndex("TenantId", "MembershipId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_access_tenant_membership_workspace");

                    b.ToTable("workspace_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_access_access_level", "access_level IN ('View', 'Edit')");
                        });
                });

            modelBuilder.Entity("PTS.Host.Persistence.Testing.TenantIsolationTestRecord", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_isolation_test_records_tenants_tenant_id");
                });

            modelBuilder.Entity("PTS.Modules.Identity.UserCredential", b =>
                {
                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PTS.Modules.Identity.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.PlatformAdministration.PlatformAdministrator", b =>
                {
                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platform_administrators_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.Tenancy.Membership", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Project", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_tenants_tenant_id");

                    b.HasOne("PTS.Modules.WorkManagement.Workspace", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkspaceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_workspaces_tenant_id_workspace_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkNotification", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RecipientMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_memberships_tenant_id_recipient_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaskId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_tasks_tenant_id_task_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTag", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tags_memberships_tenant_id_created_by_membership_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTask", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssignedMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_memberships_tenant_id_assigned_membership_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_memberships_tenant_id_created_by_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkspaceId", "ProjectId")
                        .HasPrincipalKey("TenantId", "WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_tenant_id_workspace_id_project_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskActivity", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_activities_memberships_tenant_id_actor_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaskId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_activities_tasks_tenant_id_task_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskComment", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AuthorMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_memberships_tenant_id_author_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaskId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_tasks_tenant_id_task_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskReadState", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_read_states_memberships_tenant_id_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaskId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_read_states_tasks_tenant_id_task_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkTaskTag", b =>
                {
                    b.HasOne("PTS.Modules.WorkManagement.WorkTag", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TagId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tags_tenant_id_tag_id");

                    b.HasOne("PTS.Modules.WorkManagement.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaskId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tasks_tenant_id_task_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.Workspace", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_tenants_tenant_id");
                });

            modelBuilder.Entity("PTS.Modules.WorkManagement.WorkspaceAccess", b =>
                {
                    b.HasOne("PTS.Modules.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_tenants_tenant_id");

                    b.HasOne("PTS.Modules.Tenancy.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_memberships_tenant_id_membership_id");

                    b.HasOne("PTS.Modules.WorkManagement.Workspace", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkspaceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_workspaces_tenant_id_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
